linters:
  enable:
    - depguard
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell

run:
  skip-dirs:
    - cmd/ctr/commands/run
    - cmd/ctr/commands/images
    - cmd\\ctr\\commands\\run
    - cmd\\ctr\\commands\\images

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: "io/ioutil"
