linters:
  enable:
    - depguard
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell

run:
  skip-dirs:
    - cmd/ctr/commands/run
    - cmd/ctr/commands/images
    - cmd\\ctr\\commands\\run
    - cmd\\ctr\\commands\\images

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true
    packages:
      # use "io" or "os" instead
      # https://go.dev/doc/go1.16#ioutil
      - io/ioutil
