dist: xenial
language: go

os:
- linux

go:
  - "1.12.x"

matrix:
  include:
    - os: linux

go_import_path: github.com/containerd/imgcrypt

addons:
  apt:
    packages:
      - libseccomp-dev

before_install:
  - uname -r
  - |
    pushd ..
    git clone https://github.com/containerd/containerd.git
    git clone https://github.com/containerd/project
    go get -u github.com/vbatts/git-validation
    pushd containerd
    make -j$(nproc)
    sudo make install
    sudo rm -f $(type -P ctr)
    popd
    popd

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1
  - sudo PATH=$PATH GOPATH=$GOPATH script/setup/install-runc
  - go get -u github.com/vbatts/git-validation
  - go get -u github.com/kunalkushwaha/ltag

script:
  - DCO_VERBOSITY=-q ../project/script/validate/dco
  - ../project/script/validate/fileheader ../project/
  - make check
  - make test
  - make
  - CONTAINERD=$(type -P containerd) ./script/tests/test_encryption.sh
